[workspace]
members = [
  "lastfm-models",
  "listenbrainz-models",
  "lure",
  "lure-cli",
  "lure-config",
  "lure-resources",
  "lure-service-common",
  "lure-service-lastfm",
  "lure-service-lastfm-config",
  "lure-service-listenbrainz",
  "lure-service-listenbrainz-config",
  "revolt-api",
  "revolt-models",
]
resolver = "3"

[workspace.package]
repository = "https://github.com/catuhana/lure"
authors = ["tuhana <tuhana.cat+git@gmail.com>"]
license = "MPL-2.0"
version = "1.0.0"
edition = "2021"
rust-version = "1.84"

[profile.release]
opt-level = "z"
lto = "thin"

[workspace.lints.clippy]
nursery = "warn"
unused_trait_names = "warn"
std_instead_of_core = "warn"

[workspace.dependencies]
anyhow = "1.0.95"
async-trait = "0.1.86"
futures = "0.3.31"
reqwest = "0.12.12"
secrecy = "0.10.3"
serde = "1.0.217"
serde_yml = "0.0.12"
thiserror = "2.0.11"
tokio = "1.43.0"

# [dependencies]
# tracing = "0.1.40"
# tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
